"""Generate a standalone, ABAQUS-python-compatible ``read_abaqus_odb.py`` script.

The reader logic lives in the sibling ``_read_abaqus_odb`` module (the single source of
truth, testable under CPython with ``odbAccess`` stubbed). ``write_odb_reader`` copies
that module's source verbatim, under a "generated" banner, to a flat script that runs
under ABAQUS python with zero package/path dependency::

    abaqus python read_abaqus_odb.py <job-name> <drive-nodeset>

This module is import-light (it only reads text), so calling it never triggers the
``odbAccess`` import.
"""
from __future__ import annotations

import pathlib

_SOURCE = pathlib.Path(__file__).with_name("_read_abaqus_odb.py")

BANNER = (
    "# GENERATED by microstructure_ve.backends.write_odb_reader -- do not edit.\n"
    "# Run under ABAQUS python: abaqus python read_abaqus_odb.py <job> <nodeset>\n"
)


def reader_source():
    """The verbatim source of the reader module that gets emitted."""
    return _SOURCE.read_text(encoding="utf-8")


def write_odb_reader(dest):
    """Write the standalone reader script to ``dest``; return the destination path."""
    dest = pathlib.Path(dest)
    dest.write_text(BANNER + reader_source(), encoding="utf-8")
    return dest
